# Generated by Django 3.2 on 2021-06-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_remove_cartitem_variations'),
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
