# Generated by Django 3.2.6 on 2021-09-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_productgallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
