# Generated by Django 3.2.6 on 2021-10-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_popularproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopularProduct',
        ),
    ]
