# Generated by Django 3.2.6 on 2021-10-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
    ]
