# Generated by Django 3.2 on 2021-07-26 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210726_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_joined',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_form',
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
