# Generated by Django 3.2 on 2021-06-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderproduct_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='variations',
            new_name='variation',
        ),
    ]
